<a href="https://colab.research.google.com/github/KUNALDEBNATH/Diabetes_prediction/blob/main/Diabetes_prediction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#import the libraries or dependencies
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler #to standerize data
from sklearn.model_selection import train_test_split
from sklearn import svm #model
from sklearn.metrics import accuracy_score


In [2]:
#Data collection and analysis
diabetes_dataset = pd.read_csv('/content/large_diabetes_prediction_dataset.csv', header=0)

In [3]:
diabetes_dataset.head()

gender   age  hypertension  heart_disease smoking_history    bmi  \
0  Female  80.0             0              1           never  25.19   
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [4]:
#no. of rows and col
diabetes_dataset.shape

(100000, 9)

In [5]:
#getting statistical measure of the data
diabetes_dataset.describe()

age  hypertension  heart_disease            bmi  \
count  100000.000000  100000.00000  100000.000000  100000.000000   
mean       41.885856       0.07485       0.039420      27.320767   
std        22.516840       0.26315       0.194593       6.636783   
min         0.080000       0.00000       0.000000      10.010000   
25%        24.000000       0.00000       0.000000      23.630000   
50%        43.000000       0.00000       0.000000      27.320000   
75%        60.000000       0.00000       0.000000      29.580000   
max        80.000000       1.00000       1.000000      95.690000   

         HbA1c_level  blood_glucose_level       diabetes  
count  100000.000000        100000.000000  100000.000000  
mean        5.527507           138.058060       0.085000  
std         1.070672            40.708136       0.278883  
min         3.500000            80.000000       0.000000  
25%         4.800000           100.000000       0.000000  
50%         5.800000           140.000000       0.000000  
75%         6.200000           159.000000       0.000000  
max         9.000000           300.000000       1.000000

In [ ]:
diabetes_dataset['diabetes'].value_counts()

In [10]:
#0--> Non-diabetic
#1--> Diabetic

# Select only numeric columns before calculating the mean
numeric_features = diabetes_dataset.select_dtypes(include=['number'])

diabetes_dataset.groupby('diabetes')[numeric_features.columns].mean()

age  hypertension  heart_disease        bmi  HbA1c_level  \
diabetes                                                                   
0         40.115187      0.058984       0.029235  26.887163     5.396761   
1         60.946588      0.245647       0.149059  31.988382     6.934953   

          blood_glucose_level  diabetes  
diabetes                                 
0                  132.852470       0.0  
1                  194.094706       1.0

In [12]:
X=diabetes_dataset.drop(columns='diabetes',axis=1)
Y=diabetes_dataset['diabetes']

In [13]:
print(X)
print(Y)

       gender   age  hypertension  heart_disease smoking_history    bmi  \
0      Female  80.0             0              1           never  25.19   
1      Female  54.0             0              0         No Info  27.32   
2        Male  28.0             0              0           never  27.32   
3      Female  36.0             0              0         current  23.45   
4        Male  76.0             1              1         current  20.14   
...       ...   ...           ...            ...             ...    ...   
99995  Female  80.0             0              0         No Info  27.32   
99996  Female   2.0             0              0         No Info  17.37   
99997    Male  66.0             0              0          former  27.83   
99998  Female  24.0             0              0           never  35.42   
99999  Female  57.0             0              0         current  22.43   

       HbA1c_level  blood_glucose_level  
0              6.6                  140  
1              

In [14]:
#Data Standerization
scaler = StandardScaler()

In [16]:
# Assuming X is your DataFrame
X = X.select_dtypes(include=['number'])  # Select only numeric columns

# Now apply StandardScaler
k = scaler.fit_transform(X)

In [18]:
X=k
print(X.shape)
y=diabetes_dataset['diabetes']
print(X)
print(Y)

(100000, 6)
[[ 1.69270354e+00 -2.84439447e-01  4.93637859e+00 -3.21055792e-01
   1.00170572e+00  4.77042159e-02]
 [ 5.38006427e-01 -2.84439447e-01 -2.02577655e-01 -1.15583678e-04
   1.00170572e+00 -1.42620999e+00]
 [-6.16690686e-01 -2.84439447e-01 -2.02577655e-01 -1.15583678e-04
   1.61108022e-01  4.89878478e-01]
 ...
 [ 1.07094356e+00 -2.84439447e-01 -2.02577655e-01  7.67292549e-02
   1.61108022e-01  4.16182767e-01]
 [-7.94336396e-01 -2.84439447e-01 -2.02577655e-01  1.22036126e+00
  -1.42668764e+00 -9.34905254e-01]
 [ 6.71240710e-01 -2.84439447e-01 -2.02577655e-01 -7.36921977e-01
   1.00170572e+00 -1.18055762e+00]]
0        0
1        0
2        0
3        0
4        0
        ..
99995    0
99996    0
99997    0
99998    0
99999    0
Name: diabetes, Length: 100000, dtype: int64


In [19]:
#Train Test Split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.1,stratify=Y,random_state=2)

In [20]:
print(X.shape, X_train.shape, X_test.shape)

(100000, 6) (90000, 6) (10000, 6)


In [21]:
print(X_train)
print(Y_train)
print(X_test)
print(Y_test)

[[ 0.53800643 -0.28443945 -0.20257766  2.23139826  0.90830598 -0.19794815]
 [ 1.15976641  3.51568677 -0.20257766 -0.22612981  0.90830598  3.9781421 ]
 [ 1.69270354 -0.28443945 -0.20257766 -0.94334831 -0.67948968 -1.18055762]
 ...
 [-0.4834564  -0.28443945 -0.20257766 -1.03676752 -1.89368636 -1.30338381]
 [ 0.31594929 -0.28443945 -0.20257766  0.0239926   0.16110802  0.53900895]
 [ 0.76006356 -0.28443945 -0.20257766  0.4353385  -0.49269019 -1.30338381]]
68690    0
30260    1
9235     0
46797    0
5057     0
        ..
52997    0
18231    0
63158    0
63868    0
7926     0
Name: diabetes, Length: 90000, dtype: int64
[[ 1.51505783e+00 -2.84439447e-01 -2.02577655e-01  8.12495395e-02
   5.34707000e-01 -9.34905254e-01]
 [-1.63815352e+00 -2.84439447e-01 -2.02577655e-01 -1.52495826e+00
   1.61108022e-01  5.39008951e-01]
 [ 1.69270354e+00 -2.84439447e-01  4.93637859e+00 -9.14719838e-01
  -1.42668764e+00 -1.42620999e+00]
 ...
 [-1.59374209e+00 -2.84439447e-01 -2.02577655e-01 -1.99008107e-01
   4.

In [22]:
#Training the model    SVC-SUPPORT VECTOR CLASSIFIER   KERNEL--> PARAMETER
classifier = svm.SVC(kernel='linear')

In [23]:
#training the svm classifier
classifier.fit(X_train,Y_train)

SVC(kernel='linear')

In [24]:
# accuracy score on the training data
X_train_prediction=classifier.predict(X_train)
training_data_accuracy=accuracy_score(X_train_prediction, Y_train) #comparing X with Y

In [25]:
print(training_data_accuracy)

0.9604222222222222


In [26]:
#accuracy on test data
X_test_prediction=classifier.predict(X_test)
test_data_accuracy=accuracy_score(X_test_prediction, Y_test)

In [27]:
print(test_data_accuracy)

0.9615


In [33]:
#making a predictive system
input_data = (8,125,96,0,0,0,0.232,54)
# Select the first 6 features from input_data
input_data = input_data[:6]
input_data_as_numpy_array = np.asarray(input_data)
#reshape the np array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1) #taking only one datapoint

#Standerizing the data
std_data = scaler.transform(input_data_reshaped)
print(std_data)
prediction = classifier.predict(std_data)
print(prediction)

if(prediction[0] == 0):
 print('NOT DIABETIS')
else:
  print('DIABETIS')

[[ -1.50491923 474.73133725 493.13722191  -4.11658811  -5.16267742
   -3.39142893]]
[1]
DIABETIS


/usr/local/lib/python3.10/dist-packages/sklearn/base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
